# Generated by Django 2.0.6 on 2018-08-08 16:06

import contact.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('_id', models.IntegerField(default=contact.models.number, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('emailAddress', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(blank=True, max_length=250)),
                ('connectedOn', models.CharField(max_length=50)),
                ('tags', djongo.models.fields.ListField()),
                ('owner', models.CharField(max_length=24)),
            ],
            options={
                'ordering': ('_id',),
            },
        ),
    ]
